name: Update README

on:
  workflow_dispatch: {}
  push:
    branches:
      - main
    paths:
      - ./action.yml

concurrency:
  group: readme-${{ github.ref }}-${{ github.job }}
  cancel-in-progress: true

permissions: {}

defaults:
  run:
    shell: bash

jobs:
  update-readme:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout Source
        id: checkout
        uses: actions/checkout@v5

      - name: Update README
        id: update-readme
        uses: coderrob/update-action-readme@main
        with:
          action-file-path: ./action.yml
          readme-file-path: ./README.md

      - name: Commit and Push README changes
        id: commit-and-push-readme
        uses: coderrob/commit-and-push@v1
        with:
          branch: main
          directory-path: '.'
